name: "Upload Artifacts"
description: "Uploads build artifacts to S3 bucket."

inputs:
  path:
    description: Directory containing the files to upload
    required: true
  destination:
    description: Destination path in the target storage
    required: true
  s3_bucket:
    description: S3 bucket name
    required: true
  fileserver_url:
    description: URL used by clients to download content from the file server
    required: false
    default: "https://qli-prod-artifacts.qualcomm.com"
outputs:
  url:
    description: "URL where objects are available at"

runs:
  using: docker
  image: Dockerfile
